/* Generated by tools/export_lvgl_data.mjs from data/demo-data.js.
 * Source SHA-256: c81ab795aa37af289bd5194211f0b5d226e61783da4c605379aff2da34adb425
 * Do not edit this file manually.
 */
#ifndef RF_DEMO_DATA_H
#define RF_DEMO_DATA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define RF_DEMO_CHANNEL_COUNT 4u
#define RF_DEMO_SPECTRUM_BINS 128u
#define RF_DEMO_WATERFALL_ROWS 64u
#define RF_DEMO_WATERFALL_COLS 128u
#define RF_DEMO_CLASS_COUNT 4u
#define RF_DEMO_MASK_COUNT 4u
#define RF_DEMO_MASK_COORD_SCALE 10

typedef enum {
    RF_DEMO_SOURCE_SYNTHETIC = 0,
    RF_DEMO_SOURCE_CAPTURE = 1,
} rf_demo_source_t;

typedef enum {
    RF_DEMO_STATE_ACTIVE = 0,
    RF_DEMO_STATE_SUSPECTED = 1,
    RF_DEMO_STATE_INACTIVE = 2,
} rf_demo_detection_state_t;

typedef struct {
    uint32_t sample_rate_sps;
    uint16_t rf_bandwidth_mhz_x10;
    uint16_t capture_duration_ms_x10;
    uint16_t fft_points;
    uint16_t hop_points;
} rf_demo_config_t;

typedef struct {
    const char *id;
    const char *band;
    const char *source_label;
    uint16_t center_mhz;
    uint16_t freshness_ms;
    int8_t peak_dbfs;
    int8_t noise_floor_dbfs;
    uint8_t occupancy_percent;
    uint8_t source;
    uint8_t first_mask;
    uint8_t mask_count;
} rf_demo_channel_t;

typedef struct {
    const char *id;
    const char *name;
    const char *short_name;
    uint32_t color_rgb888;
    uint8_t state;
    uint8_t confidence_percent;
    uint8_t channel_index;
} rf_demo_class_t;

typedef struct {
    uint16_t time_start_ms_x10;
    uint16_t time_end_ms_x10;
    int16_t freq_low_mhz_x10;
    int16_t freq_high_mhz_x10;
    uint8_t class_index;
    uint8_t channel_index;
} rf_demo_mask_t;

extern const rf_demo_config_t rf_demo_config;
extern const rf_demo_channel_t rf_demo_channels[RF_DEMO_CHANNEL_COUNT];
extern const rf_demo_class_t rf_demo_classes[RF_DEMO_CLASS_COUNT];
extern const rf_demo_mask_t rf_demo_masks[RF_DEMO_MASK_COUNT];
extern const uint8_t rf_demo_spectrum[RF_DEMO_CHANNEL_COUNT][RF_DEMO_SPECTRUM_BINS];
extern const uint8_t rf_demo_waterfall[RF_DEMO_CHANNEL_COUNT][RF_DEMO_WATERFALL_ROWS][RF_DEMO_WATERFALL_COLS];

#ifdef __cplusplus
}
#endif

#endif /* RF_DEMO_DATA_H */
