#include "hal_data.h"
#include "display_bringup.h"
#include "gt911_touch.h"
#include "framework/display_app.h"
#include "lvgl_app.h"

#define CPU1_MAIN_LOOP_DELAY_MS    (1U)

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    display_bringup_run();
    display_app_init();
    bool touch_available = false;
    fsp_err_t lvgl_error = FSP_ERR_NOT_OPEN;

    if (0U != g_display_diag.running)
    {
        touch_available = (FSP_SUCCESS == gt911_touch_init());
        lvgl_error = lvgl_app_init(touch_available);
        if (FSP_SUCCESS != lvgl_error)
        {
            g_display_diag.last_error = (int32_t) lvgl_error;
            g_display_diag.animation_last_error = (uint32_t) lvgl_error;
        }
    }

    while (1)
    {
        if (FSP_SUCCESS == lvgl_error)
        {
            display_app_step();
            lvgl_app_step(CPU1_MAIN_LOOP_DELAY_MS);
            const fsp_err_t backlight_error =
                display_backlight_startup_step();
            if ((FSP_SUCCESS != backlight_error) &&
                (FSP_ERR_IN_USE != backlight_error))
            {
                g_display_diag.last_error = (int32_t) backlight_error;
                g_display_diag.animation_last_error =
                    (uint32_t) backlight_error;
            }
        }
        else
        {
            display_app_step();
        }
        g_display_diag.heartbeat++;
        R_BSP_SoftwareDelay(CPU1_MAIN_LOOP_DELAY_MS, BSP_DELAY_UNITS_MILLISECONDS);
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while (FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{
}
FSP_CPP_FOOTER

#endif
